# Generated by Django 4.2.20 on 2025-03-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo1', models.CharField(max_length=100)),
                ('correo2', models.CharField(max_length=100)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('nit', models.CharField(max_length=100)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('nombre_gerente', models.CharField(max_length=100)),
                ('correo_gerente', models.CharField(max_length=100)),
                ('hecho', models.BooleanField(default=False)),
            ],
        ),
    ]
