# Generated by Django 4.2.20 on 2025-03-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='correo2',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
