# Generated by Django 4.2.20 on 2025-03-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_correo2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='nit',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
