# Generated by Django 4.2.20 on 2025-03-24 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_nit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='nombre_cliente',
        ),
    ]
